import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Share2, Copy, FileText, Image } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ResultsExporterProps {
  analysisResults: any;
  imagePreview?: string | null;
  scenario?: string;
}

export const ResultsExporter = ({ analysisResults, imagePreview, scenario }: ResultsExporterProps) => {
  const { toast } = useToast();

  const exportAsJSON = () => {
    const exportData = {
      timestamp: new Date().toISOString(),
      scenario: scenario || 'Image Analysis',
      analysis: analysisResults,
      metadata: {
        hasImage: !!imagePreview,
        exportedBy: 'DeathScanner AI',
        version: '2.0'
      }
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: 'application/json'
    });
    
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `death-analysis-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Analysis Exported",
      description: "Death analysis saved as JSON file",
    });
  };

  const exportAsText = () => {
    const textContent = `
DEATH SCANNER ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
Scenario: ${scenario || 'Image Analysis'}

RISK ASSESSMENT:
- Death Score: ${analysisResults.deathScore}/100
- Risk Level: ${analysisResults.riskLevel}
- Time to Impact: ${analysisResults.timeToImpact}

DETECTED ITEMS:
${analysisResults.detectedItems?.map((item: any) => 
  `- ${item.name}: ${item.confidence}% confidence`
).join('\n') || 'None'}

SYMPTOMS:
${analysisResults.symptoms?.join('\n- ') || 'No specific symptoms predicted'}

SURVIVAL RECOMMENDATIONS:
${analysisResults.survivalTips?.join('\n- ') || 'No specific recommendations'}

FINAL WORDS:
"${analysisResults.finalWords || 'No final words available'}"

---
Generated by DeathScanner AI v2.0
    `.trim();

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `death-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Exported",
      description: "Death analysis saved as text file",
    });
  };

  const copyToClipboard = async () => {
    const summaryText = `🔴 DEATH SCANNER ANALYSIS 🔴

Risk Level: ${analysisResults.riskLevel}
Death Score: ${analysisResults.deathScore}/100
Time to Impact: ${analysisResults.timeToImpact}

Detected: ${analysisResults.detectedItems?.map((item: any) => item.name).join(', ') || 'Unknown items'}

Key Symptoms: ${analysisResults.symptoms?.slice(0, 3).join(', ') || 'Various'}

Top Survival Tip: ${analysisResults.survivalTips?.[0] || 'Seek immediate medical attention'}

Final Words: "${analysisResults.finalWords || 'Stay strong!'}"

Generated by DeathScanner AI`;

    try {
      await navigator.clipboard.writeText(summaryText);
      toast({
        title: "Copied to Clipboard",
        description: "Analysis summary ready to share",
      });
    } catch {
      toast({
        title: "Copy Failed",
        description: "Please try the export options instead",
        variant: "destructive"
      });
    }
  };

  const shareResults = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Death Scanner Analysis',
          text: `Death Risk: ${analysisResults.riskLevel} | Score: ${analysisResults.deathScore}/100`,
          url: window.location.href
        });
      } catch {
        // User cancelled or sharing failed
        copyToClipboard();
      }
    } else {
      copyToClipboard();
    }
  };

  if (!analysisResults) return null;

  return (
    <Card className="glass-card">
      <CardHeader>
        <CardTitle className="text-card-foreground flex items-center gap-2">
          <Download className="w-5 h-5 text-primary" />
          Export & Share Results
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 gap-3">
          <Button
            onClick={exportAsJSON}
            variant="outline"
            className="border-primary text-primary hover:bg-primary hover:text-primary-foreground"
          >
            <FileText className="w-4 h-4 mr-2" />
            JSON Data
          </Button>
          
          <Button
            onClick={exportAsText}
            variant="outline"
            className="border-accent text-accent hover:bg-accent hover:text-accent-foreground"
          >
            <FileText className="w-4 h-4 mr-2" />
            Text Report
          </Button>
          
          <Button
            onClick={copyToClipboard}
            variant="outline"
            className="border-secondary text-secondary hover:bg-secondary hover:text-secondary-foreground"
          >
            <Copy className="w-4 h-4 mr-2" />
            Copy Summary
          </Button>
          
          <Button
            onClick={shareResults}
            variant="outline"
            className="border-muted-foreground text-muted-foreground hover:bg-muted hover:text-muted-foreground"
          >
            <Share2 className="w-4 h-4 mr-2" />
            Share
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};